version: "3"
services:
  selenium:
    image: selenium/hub:4.8.3
    container_name: selenium
    privileged: true
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      - docker-elk_elk
    extra_hosts:
      - "host.docker.internal:host-gateway"
  firefox:
    image: selenium/node-firefox:4.8.3
    container_name: firefox
    privileged: true
    shm_size: 2gb
    ports:
      - "5555"
    environment:
      - SE_EVENT_BUS_HOST=selenium
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_INSTANCES=1
      - SE_NODE_MAX_SESSIONS=1
      - SE_NODE_SESSION_TIMEOUT=10
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - docker-elk_elk
    depends_on:
      - selenium
    extra_hosts:
      - "host.docker.internal:host-gateway"
  chrome:
    image: selenium/node-chrome:4.8.3
    container_name: ''
    privileged: true
    shm_size: 2gb
    ports:
      - "5555"
    environment:
      - SE_EVENT_BUS_HOST=selenium
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_INSTANCES=10
      - SE_NODE_MAX_SESSIONS=5
      - SE_NODE_SESSION_TIMEOUT=10
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - docker-elk_elk
    depends_on:
      - selenium
    extra_hosts:
      - "host.docker.internal:host-gateway"
#  edge:
#    image: selenium/node-edge:4.8.3
#    shm_size: 2gb
#    environment:
#      - SE_EVENT_BUS_HOST=selenium
#      - SE_EVENT_BUS_PUBLISH_PORT=4442
#      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
#      - SE_NODE_MAX_INSTANCES=1
#      - SE_NODE_MAX_SESSIONS=1
#      - SE_NODE_SESSION_TIMEOUT=10
#    volumes:
#      - /dev/shm:/dev/shm
#    networks:
#      - selenium_grid
#    depends_on:
#      - selenium
networks:
  docker-elk_elk:
    external: true